import { X, BarChart2 } from 'lucide-react';
import { useApp } from '../store/context';
import { QUIZ_LEVELS, DIFFICULTY_CONFIG } from '../data/quizLevels';

const S = { mono: '"Share Tech Mono", monospace', orbit: 'Orbitron, monospace' };
const PAD = { padding: '14px 18px' };

const TOTAL_QUESTIONS = 30;

export function StudentDashboard() {
  const { state, dispatch } = useApp();
  if (!state.showTeacherDash) return null;

  const completed = state.completedChallenges.length;
  const totalScore = state.score;
  const wrong = state.attempts - completed;
  const pct = TOTAL_QUESTIONS > 0 ? Math.round((completed / TOTAL_QUESTIONS) * 100) : 0;

  const exportReport = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    const correctList = QUIZ_LEVELS
      .filter(q => state.completedChallenges.includes(q.level))
      .map(q => `  ✅  Q${q.level} — ${q.description} [${q.difficulty.toUpperCase()}]`)
      .join('\n') || '  None completed yet';

    const wrongList = QUIZ_LEVELS
      .filter(q => !state.completedChallenges.includes(q.level))
      .map(q => `  ❌  Q${q.level} — ${q.description} [${q.difficulty.toUpperCase()}]`)
      .join('\n') || '  All questions answered correctly!';

    const report = `
╔══════════════════════════════════════════════════════╗
║           SCILAB 360 — STUDENT PROGRESS REPORT        ║
╚══════════════════════════════════════════════════════╝

Report generated: ${dateStr} at ${timeStr}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  SCORE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Points Earned     ${totalScore} pts
  Score             ${completed} / ${TOTAL_QUESTIONS}
  Questions Correct ${completed}
  Questions Wrong   ${wrong > 0 ? wrong : 0}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  QUESTIONS ANSWERED CORRECTLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${correctList}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  QUESTIONS NOT YET COMPLETED / WRONG
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${wrongList}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Generated by SciLab 360 — Interactive Chemistry Lab
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scilab360-student-report-${now.toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{ position: 'fixed', top: 0, right: 0, bottom: 0, width: 320, display: 'flex', flexDirection: 'column', gap: 0, zIndex: 1000, background: '#0d0120', borderLeft: '1px solid #3b1d6e', boxShadow: '-4px 0 40px #00000080, -2px 0 20px #a855f720', overflowY: 'auto' }}
    >
      {/* ── Header ── */}
      <div style={{ padding: '18px 20px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #2d1b5e', flexShrink: 0 }}>
        <h2 style={{ fontFamily: S.orbit, fontWeight: 700, fontSize: 14, color: '#fff', letterSpacing: '0.15em', margin: 0 }}>
          STUDENT DASHBOARD
        </h2>
        <button onClick={() => dispatch({ type: 'TOGGLE_TEACHER' })}
          style={{ background: 'transparent', border: 'none', cursor: 'pointer', color: '#6b21a8', fontSize: 18 }}
          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = '#a855f7'; }}
          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = '#6b21a8'; }}>
          <X size={20} />
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12, padding: 16, flex: 1 }}>

        {/* ── Score banner ── */}
        <div style={{ borderRadius: 12, padding: 16, background: 'linear-gradient(135deg, #1a0533, #200040)', border: '1px solid #6d28d9', boxShadow: '0 0 20px #a855f730', textAlign: 'center' }}>
          <div style={{ fontFamily: S.orbit, fontSize: 40, fontWeight: 900, color: '#e9d5ff', lineHeight: 1, textShadow: '0 0 20px #a855f780' }}>
            {totalScore}
          </div>
          <div style={{ fontFamily: S.mono, fontSize: 11, color: '#a78bfa', marginTop: 4, letterSpacing: '0.1em' }}>TOTAL POINTS</div>

          {/* Score out of 30 */}
          <div style={{ marginTop: 14, display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#07011a', borderRadius: 10, padding: '10px 14px', border: '1px solid #2d1b5e' }}>
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ fontFamily: S.orbit, fontSize: 22, fontWeight: 900, color: '#4ade80', textShadow: '0 0 10px #4ade8060' }}>{completed}</div>
              <div style={{ fontFamily: S.mono, fontSize: 9, color: '#86efac', marginTop: 2, letterSpacing: '0.08em' }}>CORRECT</div>
            </div>
            <div style={{ width: 1, height: 36, background: '#2d1b5e' }} />
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ fontFamily: S.orbit, fontSize: 22, fontWeight: 900, color: '#f87171', textShadow: '0 0 10px #f8717160' }}>{Math.max(0, wrong)}</div>
              <div style={{ fontFamily: S.mono, fontSize: 9, color: '#fca5a5', marginTop: 2, letterSpacing: '0.08em' }}>WRONG</div>
            </div>
            <div style={{ width: 1, height: 36, background: '#2d1b5e' }} />
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ fontFamily: S.orbit, fontSize: 22, fontWeight: 900, color: '#e9d5ff', textShadow: '0 0 10px #a855f760' }}>{completed}<span style={{ fontSize: 14, color: '#9f7aea' }}>/{TOTAL_QUESTIONS}</span></div>
              <div style={{ fontFamily: S.mono, fontSize: 9, color: '#c4b5fd', marginTop: 2, letterSpacing: '0.08em' }}>SCORE</div>
            </div>
          </div>

          <div style={{ marginTop: 12, height: 8, background: '#1e0b3e', borderRadius: 999, overflow: 'hidden' }}>
            <div style={{ height: '100%', width: `${pct}%`, background: 'linear-gradient(90deg, #7c3aed, #ec4899)', borderRadius: 999, transition: 'width 0.5s', boxShadow: '0 0 8px #a855f7' }} />
          </div>
          <div style={{ fontFamily: S.mono, fontSize: 11, color: '#c4b5fd', marginTop: 6 }}>
            {pct}% complete
          </div>
        </div>

        {/* ── Progress by difficulty breakdown ── */}
        <div style={{ borderRadius: 12, ...PAD, background: '#130929', border: '1px solid #2d1b5e' }}>
          <p style={{ fontFamily: S.mono, fontSize: 10, fontWeight: 700, color: '#a855f7', letterSpacing: '0.15em', marginBottom: 12 }}>PROGRESS BY DIFFICULTY</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {(['easy', 'medium', 'hard'] as const).map(d => {
              const cfg = DIFFICULTY_CONFIG[d];
              const levelsInD = QUIZ_LEVELS.filter(q => q.difficulty === d);
              const doneInD = levelsInD.filter(q => state.completedChallenges.includes(q.level)).length;
              const dpct = levelsInD.length > 0 ? (doneInD / levelsInD.length) * 100 : 0;
              return (
                <div key={d}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                    <span style={{ fontFamily: S.mono, fontSize: 12, color: cfg.color, fontWeight: 700 }}>{cfg.emoji} {cfg.label}</span>
                    <span style={{ fontFamily: S.mono, fontSize: 12, color: '#c4b5fd' }}>{doneInD}/{levelsInD.length}</span>
                  </div>
                  <div style={{ height: 6, background: '#1e0b3e', borderRadius: 999, overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${dpct}%`, background: cfg.color, borderRadius: 999, boxShadow: `0 0 6px ${cfg.color}`, transition: 'width 0.5s' }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* ── Student progress list sectioned by difficulty ── */}
        {(['easy', 'medium', 'hard'] as const).map(d => {
          const cfg = DIFFICULTY_CONFIG[d];
          const levelsInD = QUIZ_LEVELS.filter(q => q.difficulty === d);
          return (
            <div key={d} style={{ borderRadius: 12, ...PAD, background: '#130929', border: `1px solid ${cfg.border}` }}>
              <p style={{ fontFamily: S.mono, fontSize: 10, fontWeight: 700, color: cfg.color, letterSpacing: '0.15em', marginBottom: 10 }}>
                {cfg.emoji} {cfg.label.toUpperCase()} — LEVELS {levelsInD[0].level}–{levelsInD[levelsInD.length - 1].level}
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
                {levelsInD.map(q => {
                  const done = state.completedChallenges.includes(q.level);
                  return (
                    <div key={q.level} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '6px 10px', borderRadius: 8, background: done ? '#0f0620' : '#07011a', border: `1px solid ${done ? '#3b1d6e' : '#1e0b3e'}` }}>
                      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                        <span style={{ fontFamily: S.mono, fontSize: 10, color: '#6b21a8', minWidth: 24 }}>L{q.level}</span>
                        <span style={{ fontFamily: S.mono, fontSize: 11, color: done ? '#c4b5fd' : '#4c1d95' }}>{q.description}</span>
                      </div>
                      <span style={{
                        fontSize: 13,
                        fontWeight: 700,
                        color: done ? cfg.color : '#2d1b5e',
                      }}>
                        {done ? '✓' : '○'}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}

        {/* ── Download button ── */}
        <button onClick={exportReport}
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: '14px 16px', borderRadius: 12, cursor: 'pointer', fontFamily: S.orbit, fontWeight: 700, fontSize: 13, letterSpacing: '0.08em', color: '#e9d5ff', background: 'linear-gradient(135deg, #3b0764, #4c1d95)', border: '1px solid #a855f7', boxShadow: '0 0 16px #a855f740', transition: 'all 0.15s' }}
          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 0 24px #a855f7aa'; (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1.02)'; }}
          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 0 16px #a855f740'; (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1)'; }}>
          <BarChart2 size={16} />
          DOWNLOAD MY REPORT
        </button>
      </div>
    </div>
  );
}
