import { X, BarChart2 } from 'lucide-react';
import { useApp } from '../../shared/store/context';
import { useTheme } from '../../shared/store/theme';
import { QUIZ_LEVELS, DIFFICULTY_CONFIG } from '../../shared/data/quizLevels';

const TOTAL_QUESTIONS = 30;

function useIsMobile() {
  if (typeof window === 'undefined') return false;
  return window.innerWidth < 768;
}

export function StudentDashboard() {
  const { state, dispatch } = useApp();
  const { theme } = useTheme();
  const isMobile = useIsMobile();
  if (!state.showTeacherDash) return null;

  const completed = state.completedChallenges.length;
  const totalScore = state.score;
  const wrong = state.attempts - completed;
  const pct = TOTAL_QUESTIONS > 0 ? Math.round((completed / TOTAL_QUESTIONS) * 100) : 0;

  const diffColors: Record<string, { bg: string; text: string; border: string }> = {
    easy: { bg: theme.isDark ? '#0a2a1a' : '#f0fdf4', text: '#16a34a', border: theme.isDark ? '#166534' : '#bbf7d0' },
    medium: { bg: theme.isDark ? '#2a2410' : '#fffbeb', text: '#d97706', border: theme.isDark ? '#854d0e' : '#fde68a' },
    hard: { bg: theme.isDark ? '#2a1a1a' : '#fef2f2', text: '#dc2626', border: theme.isDark ? '#7f1d1d' : '#fecaca' },
  };

  const exportReport = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    const correctList = QUIZ_LEVELS
      .filter(q => state.completedChallenges.includes(q.level))
      .map(q => `  Q${q.level} - ${q.description} [${q.difficulty.toUpperCase()}]`)
      .join('\n') || '  None completed yet';

    const wrongList = QUIZ_LEVELS
      .filter(q => !state.completedChallenges.includes(q.level))
      .map(q => `  Q${q.level} - ${q.description} [${q.difficulty.toUpperCase()}]`)
      .join('\n') || '  All questions answered correctly!';

    const report = `
SCILAB 360 - STUDENT PROGRESS REPORT
=====================================

Report generated: ${dateStr} at ${timeStr}

SCORE SUMMARY
-------------
  Points Earned     ${totalScore} pts
  Score             ${completed} / ${TOTAL_QUESTIONS}
  Questions Correct ${completed}
  Questions Wrong   ${wrong > 0 ? wrong : 0}

QUESTIONS ANSWERED CORRECTLY
----------------------------
${correctList}

QUESTIONS NOT YET COMPLETED
----------------------------
${wrongList}

Generated by SciLab 360
`.trim();

    const blob = new Blob(['\uFEFF' + report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scilab360-student-report-${now.toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0, right: 0, bottom: 0,
        width: isMobile ? '100%' : 340,
        display: 'flex', flexDirection: 'column',
        zIndex: 1000,
        background: theme.surface,
        borderLeft: isMobile ? 'none' : `1px solid ${theme.border}`,
        boxShadow: '-4px 0 24px rgba(0,0,0,0.08)',
        overflowY: 'auto',
      }}
    >
      {/* Header */}
      <div style={{ padding: '18px 20px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: `1px solid ${theme.border}`, flexShrink: 0, background: theme.surfaceAlt }}>
        <h2 style={{ fontFamily: '"Playfair Display", sans-serif', fontWeight: 800, fontSize: 16, color: theme.logoText, letterSpacing: '-0.01em', margin: 0 }}>
          My Progress
        </h2>
        <button onClick={() => dispatch({ type: 'TOGGLE_TEACHER' })}
          style={{ background: 'transparent', border: 'none', cursor: 'pointer', color: theme.textTertiary, fontSize: 18 }}
          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = theme.textSecondary; }}
          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = theme.textTertiary; }}>
          <X size={20} />
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 14, padding: 18, flex: 1 }}>

        {/* Score banner */}
        <div style={{ borderRadius: 16, padding: 20, background: theme.accentBg, border: `1px solid ${theme.accentBorder}`, textAlign: 'center' }}>
          <div style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 48, fontWeight: 900, color: theme.accent, lineHeight: 1 }}>
            {totalScore}
          </div>
          <div style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 12, color: theme.accentLight, marginTop: 4, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Total Points</div>

          <div style={{ marginTop: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: theme.surface, borderRadius: 12, padding: '12px 14px', border: `1px solid ${theme.border}` }}>
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 24, fontWeight: 900, color: '#16a34a' }}>{completed}</div>
              <div style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 10, color: theme.isDark ? '#4ade80' : '#86efac', marginTop: 2, fontWeight: 600, textTransform: 'uppercase' }}>Correct</div>
            </div>
            <div style={{ width: 1, height: 36, background: theme.border }} />
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 24, fontWeight: 900, color: '#ef4444' }}>{Math.max(0, wrong)}</div>
              <div style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 10, color: theme.isDark ? '#f87171' : '#fca5a5', marginTop: 2, fontWeight: 600, textTransform: 'uppercase' }}>Wrong</div>
            </div>
            <div style={{ width: 1, height: 36, background: theme.border }} />
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 24, fontWeight: 900, color: theme.accent }}>{completed}<span style={{ fontSize: 14, color: theme.textTertiary }}>/{TOTAL_QUESTIONS}</span></div>
              <div style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 10, color: theme.accentLight, marginTop: 2, fontWeight: 600, textTransform: 'uppercase' }}>Score</div>
            </div>
          </div>

          <div style={{ marginTop: 14, height: 8, background: theme.progressBg, borderRadius: 999, overflow: 'hidden' }}>
            <div style={{ height: '100%', width: `${pct}%`, background: theme.accent, borderRadius: 999, transition: 'width 0.5s' }} />
          </div>
          <div style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 12, color: theme.textSecondary, marginTop: 8, fontWeight: 500 }}>
            {pct}% complete
          </div>
        </div>

        {/* Progress by difficulty */}
        <div style={{ borderRadius: 14, padding: '14px 18px', background: theme.surfaceAlt, border: `1px solid ${theme.border}` }}>
          <p style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 11, fontWeight: 800, color: theme.accent, letterSpacing: '0.05em', marginBottom: 12, textTransform: 'uppercase' }}>Progress by Difficulty</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {(['easy', 'medium', 'hard'] as const).map(d => {
              const cfg = DIFFICULTY_CONFIG[d];
              const dc = diffColors[d];
              const levelsInD = QUIZ_LEVELS.filter(q => q.difficulty === d);
              const doneInD = levelsInD.filter(q => state.completedChallenges.includes(q.level)).length;
              const dpct = levelsInD.length > 0 ? (doneInD / levelsInD.length) * 100 : 0;
              return (
                <div key={d}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                    <span style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 13, color: dc.text, fontWeight: 700 }}>{cfg.emoji} {cfg.label}</span>
                    <span style={{ fontFamily: '"Space Mono", monospace', fontSize: 12, color: theme.textSecondary }}>{doneInD}/{levelsInD.length}</span>
                  </div>
                  <div style={{ height: 6, background: theme.progressBg, borderRadius: 999, overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${dpct}%`, background: dc.text, borderRadius: 999, transition: 'width 0.5s' }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Student progress list */}
        {(['easy', 'medium', 'hard'] as const).map(d => {
          const cfg = DIFFICULTY_CONFIG[d];
          const dc = diffColors[d];
          const levelsInD = QUIZ_LEVELS.filter(q => q.difficulty === d);
          return (
            <div key={d} style={{ borderRadius: 14, padding: '14px 18px', background: theme.surface, border: `1px solid ${dc.border}` }}>
              <p style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 11, fontWeight: 800, color: dc.text, letterSpacing: '0.05em', marginBottom: 10, textTransform: 'uppercase' }}>
                {cfg.emoji} {cfg.label} - Levels {levelsInD[0].level}-{levelsInD[levelsInD.length - 1].level}
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
                {levelsInD.map(q => {
                  const done = state.completedChallenges.includes(q.level);
                  return (
                    <div key={q.level} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '7px 10px', borderRadius: 8, background: done ? dc.bg : theme.surfaceAlt, border: `1px solid ${done ? dc.border : theme.borderLight}` }}>
                      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                        <span style={{ fontFamily: '"Space Mono", monospace', fontSize: 11, color: theme.textTertiary, minWidth: 24 }}>L{q.level}</span>
                        <span style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 12, color: done ? theme.textSecondary : theme.textTertiary }}>{q.description}</span>
                      </div>
                      <span style={{
                        fontSize: 13,
                        fontWeight: 700,
                        color: done ? dc.text : theme.border,
                      }}>
                        {done ? '\u2713' : '\u25CB'}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}

        {/* Download button */}
        <button onClick={exportReport}
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: '14px 16px', borderRadius: 12, cursor: 'pointer', fontFamily: '"Playfair Display", sans-serif', fontWeight: 800, fontSize: 14, color: '#ffffff', background: theme.accent, border: 'none', transition: 'all 0.2s' }}
          onMouseEnter={e => { e.currentTarget.style.background = theme.accentDark; e.currentTarget.style.transform = 'scale(1.02)'; }}
          onMouseLeave={e => { e.currentTarget.style.background = theme.accent; e.currentTarget.style.transform = 'scale(1)'; }}>
          <BarChart2 size={16} />
          Download My Report
        </button>
      </div>
    </div>
  );
}
