import { X, BarChart2 } from 'lucide-react';
import { useApp } from '../../shared/store/context';
import { QUIZ_LEVELS, DIFFICULTY_CONFIG } from '../../shared/data/quizLevels';

const diffColors: Record<string, { bg: string; text: string; border: string }> = {
  easy: { bg: '#f0fdf4', text: '#16a34a', border: '#bbf7d0' },
  medium: { bg: '#fffbeb', text: '#d97706', border: '#fde68a' },
  hard: { bg: '#fef2f2', text: '#dc2626', border: '#fecaca' },
};

export function TeacherDashboard() {
  const { state, dispatch } = useApp();
  if (!state.showTeacherDash) return null;

  const completed = state.completedChallenges.length;
  const total = QUIZ_LEVELS.length;
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;

  const exportReport = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    const completedDetails = QUIZ_LEVELS
      .filter(q => state.completedChallenges.includes(q.level))
      .map(q => `  Level ${q.level} - ${q.description} (${q.difficulty})`)
      .join('\n') || '  None completed yet';

    const remaining = QUIZ_LEVELS
      .filter(q => !state.completedChallenges.includes(q.level))
      .map(q => `  Level ${q.level} - ${q.description} (${q.difficulty})`)
      .join('\n') || '  All levels completed!';

    const diffStats = (['easy', 'medium', 'hard'] as const).map(d => {
      const levelsInDiff = QUIZ_LEVELS.filter(q => q.difficulty === d);
      const doneInDiff = levelsInDiff.filter(q => state.completedChallenges.includes(q.level));
      return `  ${DIFFICULTY_CONFIG[d].emoji}  ${d.charAt(0).toUpperCase() + d.slice(1)}: ${doneInDiff.length} of ${levelsInDiff.length} completed`;
    }).join('\n');

    const report = `
SCILAB 360 - STUDENT PROGRESS REPORT
=====================================

Report generated: ${dateStr} at ${timeStr}
Session mode: ${state.mode === 'quiz' ? 'Quiz Mode' : 'Free Play'}

OVERALL PERFORMANCE
-------------------
  Total Score       ${state.score} points
  Challenges Done   ${completed} out of ${total} (${pct}%)
  Current Level     ${state.level}
  Total Attempts    ${state.attempts}
  Atoms Placed      ${state.atomCount}
  Active Formula    ${state.formula || 'None'}

PROGRESS BY DIFFICULTY
----------------------
${diffStats}

COMPLETED CHALLENGES
--------------------
${completedDetails}

REMAINING CHALLENGES
--------------------
${remaining}

Generated by SciLab 360
`.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scilab360-report-${now.toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{ position: 'fixed', top: 0, right: 0, bottom: 0, width: 340, display: 'flex', flexDirection: 'column', zIndex: 1000, background: '#ffffff', borderLeft: '1px solid #D4C8B4', boxShadow: '-4px 0 24px rgba(0,0,0,0.08)', overflowY: 'auto' }}
    >
      {/* Header */}
      <div style={{ padding: '18px 20px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #D4C8B4', flexShrink: 0, background: theme.surface }}>
        <h2 style={{ fontFamily: '"Playfair Display", sans-serif', fontWeight: 800, fontSize: 16, color: theme.text, margin: 0 }}>
          Teacher Dashboard
        </h2>
        <button onClick={() => dispatch({ type: 'TOGGLE_TEACHER' })}
          style={{ background: 'transparent', border: 'none', cursor: 'pointer', color: theme.textTertiary, fontSize: 18 }}
          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = '#475569'; }}
          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = theme.textTertiary; }}>
          <X size={20} />
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 14, padding: 18, flex: 1 }}>

        {/* Score banner */}
        <div style={{ borderRadius: 16, padding: 20, background: theme.accentBg, border: '1px solid #9AD4D0', textAlign: 'center' }}>
          <div style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 48, fontWeight: 900, color: theme.accentDark, lineHeight: 1 }}>
            {state.score}
          </div>
          <div style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 12, color: '#3BA8A2', marginTop: 4, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Total Points</div>
          <div style={{ marginTop: 14, height: 8, background: theme.progressBg, borderRadius: 999, overflow: 'hidden' }}>
            <div style={{ height: '100%', width: `${pct}%`, background: theme.accent, borderRadius: 999, transition: 'width 0.5s' }} />
          </div>
          <div style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 12, color: theme.textSecondary, marginTop: 8, fontWeight: 500 }}>
            {completed}/{total} challenges complete ({pct}%)
          </div>
        </div>

        {/* Summary grid */}
        <div style={{ borderRadius: 14, padding: '14px 18px', background: theme.surface, border: `1px solid ${theme.border}` }}>
          <p style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 11, fontWeight: 800, color: theme.accentDark, letterSpacing: '0.05em', marginBottom: 12, textTransform: 'uppercase' }}>Class Summary</p>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            {[
              ['Students', '1'],
              ['Avg Score', String(state.score)],
              ['Avg Level', String(state.level)],
              ['Completed', `${completed}/${total}`],
            ].map(([label, value]) => (
              <div key={label} style={{ padding: '10px 12px', borderRadius: 10, background: '#ffffff', border: `1px solid ${theme.border}` }}>
                <p style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 10, color: theme.textTertiary, marginBottom: 4, textTransform: 'uppercase' }}>{label}</p>
                <p style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 22, fontWeight: 800, color: '#0E6B68', margin: 0 }}>{value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Difficulty breakdown */}
        <div style={{ borderRadius: 14, padding: '14px 18px', background: theme.surface, border: `1px solid ${theme.border}` }}>
          <p style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 11, fontWeight: 800, color: theme.accentDark, letterSpacing: '0.05em', marginBottom: 12, textTransform: 'uppercase' }}>Progress by Difficulty</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {(['easy', 'medium', 'hard'] as const).map(d => {
              const cfg = DIFFICULTY_CONFIG[d];
              const dc = diffColors[d];
              const levelsInD = QUIZ_LEVELS.filter(q => q.difficulty === d);
              const doneInD = levelsInD.filter(q => state.completedChallenges.includes(q.level)).length;
              const dpct = levelsInD.length > 0 ? (doneInD / levelsInD.length) * 100 : 0;
              return (
                <div key={d}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                    <span style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 13, color: dc.text, fontWeight: 700 }}>{cfg.emoji} {cfg.label}</span>
                    <span style={{ fontFamily: '"Space Mono", monospace', fontSize: 12, color: theme.textSecondary }}>{doneInD}/{levelsInD.length}</span>
                  </div>
                  <div style={{ height: 6, background: theme.progressBg, borderRadius: 999, overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${dpct}%`, background: dc.text, borderRadius: 999, transition: 'width 0.5s' }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Progress list */}
        <div style={{ borderRadius: 14, padding: '14px 18px', background: theme.surface, border: `1px solid ${theme.border}` }}>
          <p style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 11, fontWeight: 800, color: theme.accentDark, letterSpacing: '0.05em', marginBottom: 12, textTransform: 'uppercase' }}>Student Progress</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
            {QUIZ_LEVELS.map(q => {
              const done = state.completedChallenges.includes(q.level);
              const dc = diffColors[q.difficulty] ?? { bg: '#FDFAF5', text: '#566860', border: '#D4C8B4' };
              return (
                <div key={q.level} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '7px 10px', borderRadius: 8, background: done ? dc.bg : theme.surface, border: `1px solid ${done ? dc.border : theme.borderLight}` }}>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <span style={{ fontFamily: '"Space Mono", monospace', fontSize: 11, color: theme.textTertiary }}>L{q.level}</span>
                    <span style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 12, color: done ? theme.textSecondary : theme.textTertiary }}>{q.description}</span>
                  </div>
                  <span style={{ fontSize: 14, fontWeight: 700, color: done ? dc.text : '#D4C8B4' }}>
                    {done ? '\u2713' : '\u25CB'}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Session stats */}
        <div style={{ borderRadius: 14, padding: '14px 18px', background: theme.surface, border: `1px solid ${theme.border}` }}>
          <p style={{ fontFamily: '"Playfair Display", sans-serif', fontSize: 11, fontWeight: 800, color: theme.accentDark, letterSpacing: '0.05em', marginBottom: 12, textTransform: 'uppercase' }}>Session Stats</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {[
              ['Atoms Placed', state.atomCount],
              ['Total Attempts', state.attempts],
              ['Current Mode', state.mode === 'quiz' ? 'Quiz Mode' : 'Free Play'],
              ['Current Formula', state.formula || 'None'],
              ['Bonds Formed', state.bonds.length],
            ].map(([label, value]) => (
              <div key={String(label)} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 13, color: theme.textTertiary }}>{label}</span>
                <span style={{ fontFamily: '"Space Mono", monospace', fontSize: 13, fontWeight: 700, color: theme.text }}>{String(value)}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Export button */}
        <button onClick={exportReport}
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: '14px 16px', borderRadius: 12, cursor: 'pointer', fontFamily: '"Playfair Display", sans-serif', fontWeight: 800, fontSize: 14, color: '#ffffff', background: '#0E6B68', border: 'none', transition: 'all 0.2s' }}
          onMouseEnter={e => { e.currentTarget.style.background = '#094E4C'; e.currentTarget.style.transform = 'scale(1.02)'; }}
          onMouseLeave={e => { e.currentTarget.style.background = '#0E6B68'; e.currentTarget.style.transform = 'scale(1)'; }}>
          <BarChart2 size={16} />
          Download Progress Report
        </button>
      </div>
    </div>
  );
}
