import { X, BarChart2 } from 'lucide-react';
import { useApp } from '../store/context';
import { QUIZ_LEVELS, DIFFICULTY_CONFIG } from '../data/quizLevels';

const S = { mono: '"Share Tech Mono", monospace', orbit: 'Orbitron, monospace' };
const PAD = { padding: '14px 18px' };

export function TeacherDashboard() {
  const { state, dispatch } = useApp();
  if (!state.showTeacherDash) return null;

  const completed = state.completedChallenges.length;
  const total = QUIZ_LEVELS.length;
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;

  const exportReport = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    const completedDetails = QUIZ_LEVELS
      .filter(q => state.completedChallenges.includes(q.level))
      .map(q => `  ✅  Level ${q.level} — ${q.description} (${q.difficulty})`)
      .join('\n') || '  None completed yet';

    const remaining = QUIZ_LEVELS
      .filter(q => !state.completedChallenges.includes(q.level))
      .map(q => `  ⏳  Level ${q.level} — ${q.description} (${q.difficulty})`)
      .join('\n') || '  All levels completed!';

    const diffStats = (['easy', 'medium', 'hard'] as const).map(d => {
      const levelsInDiff = QUIZ_LEVELS.filter(q => q.difficulty === d);
      const doneInDiff = levelsInDiff.filter(q => state.completedChallenges.includes(q.level));
      return `  ${DIFFICULTY_CONFIG[d].emoji}  ${d.charAt(0).toUpperCase() + d.slice(1)}: ${doneInDiff.length} of ${levelsInDiff.length} completed`;
    }).join('\n');

    const report = `
╔══════════════════════════════════════════════════════╗
║           SCILAB 360 — STUDENT PROGRESS REPORT        ║
╚══════════════════════════════════════════════════════╝

Report generated: ${dateStr} at ${timeStr}
Student: Student #1
Session mode: ${state.mode === 'quiz' ? 'Quiz Mode' : 'Free Play'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  OVERALL PERFORMANCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Total Score       ${state.score} points
  Challenges Done   ${completed} out of ${total} (${pct}%)
  Current Level     ${state.level}
  Total Attempts    ${state.attempts}
  Atoms Placed      ${state.atomCount}
  Active Formula    ${state.formula || 'None'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  PROGRESS BY DIFFICULTY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${diffStats}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  COMPLETED CHALLENGES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${completedDetails}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  REMAINING CHALLENGES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${remaining}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  TEACHER NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  The student has completed ${pct}% of all challenges.
  ${state.attempts > 0 ? `They made ${state.attempts} attempt(s) in this session.` : ''}
  ${state.score > 150 ? 'Great performance — encourage harder difficulty challenges!' : state.score > 0 ? 'Making good progress. Keep encouraging exploration.' : 'Just getting started — guide them through the basics.'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Generated by SciLab 360 — Interactive Chemistry Lab
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scilab360-report-${now.toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{ position: 'fixed', top: 0, right: 0, bottom: 0, width: 320, display: 'flex', flexDirection: 'column', gap: 0, zIndex: 1000, background: '#0d0120', borderLeft: '1px solid #3b1d6e', boxShadow: '-4px 0 40px #00000080, -2px 0 20px #a855f720', overflowY: 'auto' }}
    >
      {/* ── Header ── */}
      <div style={{ padding: '18px 20px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #2d1b5e', flexShrink: 0 }}>
        <h2 style={{ fontFamily: S.orbit, fontWeight: 700, fontSize: 14, color: '#fff', letterSpacing: '0.15em', margin: 0 }}>
          TEACHER DASHBOARD
        </h2>
        <button onClick={() => dispatch({ type: 'TOGGLE_TEACHER' })}
          style={{ background: 'transparent', border: 'none', cursor: 'pointer', color: '#6b21a8', fontSize: 18 }}
          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = '#a855f7'; }}
          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = '#6b21a8'; }}>
          <X size={20} />
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12, padding: 16, flex: 1 }}>

        {/* ── Overall score banner ── */}
        <div style={{ borderRadius: 12, padding: 16, background: 'linear-gradient(135deg, #1a0533, #200040)', border: '1px solid #6d28d9', boxShadow: '0 0 20px #a855f730', textAlign: 'center' }}>
          <div style={{ fontFamily: S.orbit, fontSize: 40, fontWeight: 900, color: '#e9d5ff', lineHeight: 1, textShadow: '0 0 20px #a855f780' }}>
            {state.score}
          </div>
          <div style={{ fontFamily: S.mono, fontSize: 11, color: '#a78bfa', marginTop: 4, letterSpacing: '0.1em' }}>TOTAL POINTS</div>
          <div style={{ marginTop: 12, height: 8, background: '#1e0b3e', borderRadius: 999, overflow: 'hidden' }}>
            <div style={{ height: '100%', width: `${pct}%`, background: 'linear-gradient(90deg, #7c3aed, #ec4899)', borderRadius: 999, transition: 'width 0.5s', boxShadow: '0 0 8px #a855f7' }} />
          </div>
          <div style={{ fontFamily: S.mono, fontSize: 11, color: '#c4b5fd', marginTop: 6 }}>
            {completed}/{total} challenges complete ({pct}%)
          </div>
        </div>

        {/* ── Class summary grid ── */}
        <div style={{ borderRadius: 12, ...PAD, background: '#130929', border: '1px solid #2d1b5e' }}>
          <p style={{ fontFamily: S.mono, fontSize: 10, fontWeight: 700, color: '#a855f7', letterSpacing: '0.15em', marginBottom: 12 }}>CLASS SUMMARY</p>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            {[
              ['Students', '1'],
              ['Avg Score', String(state.score)],
              ['Avg Level', String(state.level)],
              ['Completed', `${completed}/${total}`],
            ].map(([label, value]) => (
              <div key={label} style={{ padding: '10px 12px', borderRadius: 10, background: '#07011a', border: '1px solid #1e0b3e' }}>
                <p style={{ fontFamily: S.mono, fontSize: 10, color: '#6b21a8', marginBottom: 4 }}>{label}</p>
                <p style={{ fontFamily: S.orbit, fontSize: 22, fontWeight: 700, color: '#a855f7', margin: 0, textShadow: '0 0 10px #a855f760' }}>{value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ── Difficulty breakdown ── */}
        <div style={{ borderRadius: 12, ...PAD, background: '#130929', border: '1px solid #2d1b5e' }}>
          <p style={{ fontFamily: S.mono, fontSize: 10, fontWeight: 700, color: '#a855f7', letterSpacing: '0.15em', marginBottom: 12 }}>PROGRESS BY DIFFICULTY</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {(['easy', 'medium', 'hard'] as const).map(d => {
              const cfg = DIFFICULTY_CONFIG[d];
              const levelsInD = QUIZ_LEVELS.filter(q => q.difficulty === d);
              const doneInD = levelsInD.filter(q => state.completedChallenges.includes(q.level)).length;
              const dpct = levelsInD.length > 0 ? (doneInD / levelsInD.length) * 100 : 0;
              return (
                <div key={d}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                    <span style={{ fontFamily: S.mono, fontSize: 12, color: cfg.color, fontWeight: 700 }}>{cfg.emoji} {cfg.label}</span>
                    <span style={{ fontFamily: S.mono, fontSize: 12, color: '#c4b5fd' }}>{doneInD}/{levelsInD.length}</span>
                  </div>
                  <div style={{ height: 6, background: '#1e0b3e', borderRadius: 999, overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${dpct}%`, background: cfg.color, borderRadius: 999, boxShadow: `0 0 6px ${cfg.color}`, transition: 'width 0.5s' }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* ── Student progress list ── */}
        <div style={{ borderRadius: 12, ...PAD, background: '#130929', border: '1px solid #2d1b5e' }}>
          <p style={{ fontFamily: S.mono, fontSize: 10, fontWeight: 700, color: '#a855f7', letterSpacing: '0.15em', marginBottom: 12 }}>STUDENT #1 PROGRESS</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {QUIZ_LEVELS.map(q => {
              const done = state.completedChallenges.includes(q.level);
              const cfg = DIFFICULTY_CONFIG[q.difficulty];
              return (
                <div key={q.level} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '6px 10px', borderRadius: 8, background: done ? '#0f0620' : '#07011a', border: `1px solid ${done ? '#3b1d6e' : '#1e0b3e'}` }}>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <span style={{ fontFamily: S.mono, fontSize: 10, color: '#6b21a8' }}>L{q.level}</span>
                    <span style={{ fontFamily: S.mono, fontSize: 11, color: done ? '#c4b5fd' : '#4c1d95' }}>{q.description}</span>
                    <span style={{ fontSize: 9 }}>{cfg.emoji}</span>
                  </div>
                  <span style={{ fontSize: 14, fontWeight: 700, color: done ? '#a855f7' : '#2d1b5e' }}>
                    {done ? '✓' : '○'}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        {/* ── Session stats ── */}
        <div style={{ borderRadius: 12, ...PAD, background: '#130929', border: '1px solid #2d1b5e' }}>
          <p style={{ fontFamily: S.mono, fontSize: 10, fontWeight: 700, color: '#a855f7', letterSpacing: '0.15em', marginBottom: 12 }}>SESSION STATS</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {[
              ['Atoms Placed', state.atomCount],
              ['Total Attempts', state.attempts],
              ['Current Mode', state.mode === 'quiz' ? 'Quiz Mode' : 'Free Play'],
              ['Current Formula', state.formula || 'None'],
              ['Bonds Formed', state.bonds.length],
            ].map(([label, value]) => (
              <div key={String(label)} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontFamily: S.mono, fontSize: 12, color: '#9f7aea' }}>{label}</span>
                <span style={{ fontFamily: S.mono, fontSize: 12, fontWeight: 700, color: '#e9d5ff' }}>{String(value)}</span>
              </div>
            ))}
          </div>
        </div>

        {/* ── Export button ── */}
        <button onClick={exportReport}
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: '14px 16px', borderRadius: 12, cursor: 'pointer', fontFamily: S.orbit, fontWeight: 700, fontSize: 13, letterSpacing: '0.08em', color: '#e9d5ff', background: 'linear-gradient(135deg, #3b0764, #4c1d95)', border: '1px solid #a855f7', boxShadow: '0 0 16px #a855f740', transition: 'all 0.15s' }}
          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 0 24px #a855f7aa'; (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1.02)'; }}
          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.boxShadow = '0 0 16px #a855f740'; (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1)'; }}>
          <BarChart2 size={16} />
          DOWNLOAD PROGRESS REPORT
        </button>
        <p style={{ fontFamily: S.mono, fontSize: 10, color: '#4c1d95', textAlign: 'center', marginTop: -8 }}>
          Downloads a readable .txt file — no tech knowledge needed
        </p>
      </div>
    </div>
  );
}
